spring:
  application:
      name: summary
  data:
    mongodb:
      uri: mongodb+srv://kevin:HU1017hu@time-sheet-cluster-foqwp.mongodb.net/test?retryWrites=true&w=majority
      database: Project

server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

feign:
  hystrix:
    enabled: true